name: Build APK

on:  
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          
      - name: Install dependencies
        run: yarn install

      - name: Expo Doctor
        run: expo doctor

      - name: Generate Prebuild
        run: expo prebuild --no-install --platform android && yarn install

      - name: Generate Bundle
        run: mkdir android/app/src/main/assets && yarn react-native bundle --dev true --platform android --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res

      - name: Setup JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - run: sdkmanager "ndk;21.4.7075529"

      - name: Build project with Gradle
        run: cd android && chmod +x ./gradlew && ./gradlew app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
