package com.cutthecord.commands;

import java.util.ArrayList;
import java.util.List;

public class Replacements {

    public static final List<CTCCommands.StrPair> FLIP = new ArrayList<CTCCommands.StrPair>() {{
        add(new CTCCommands.StrPair("a", "ɐ"));
        add(new CTCCommands.StrPair("b", "q"));
        add(new CTCCommands.StrPair("c", "ɔ"));
        add(new CTCCommands.StrPair("d", "p"));
        add(new CTCCommands.StrPair("e", "ǝ"));
        add(new CTCCommands.StrPair("f", "ɟ"));
        add(new CTCCommands.StrPair("g", "ƃ"));
        add(new CTCCommands.StrPair("h", "ɥ"));
        add(new CTCCommands.StrPair("i", "ı"));
        add(new CTCCommands.StrPair("j", "ɾ"));
        add(new CTCCommands.StrPair("k", "ʞ"));
        add(new CTCCommands.StrPair("l", "ן"));
        add(new CTCCommands.StrPair("m", "ɯ"));
        add(new CTCCommands.StrPair("n", "u"));
        //add(new CTCCommands.StrPair("o", "o"));
        add(new CTCCommands.StrPair("p", "d"));
        add(new CTCCommands.StrPair("q", "b"));
        add(new CTCCommands.StrPair("r", "ɹ"));
        //add(new CTCCommands.StrPair("s", "s"));
        add(new CTCCommands.StrPair("t", "ʇ"));
        add(new CTCCommands.StrPair("u", "n"));
        add(new CTCCommands.StrPair("v", "ʌ"));
        add(new CTCCommands.StrPair("w", "ʍ"));
        //add(new CTCCommands.StrPair("x", "x"));
        add(new CTCCommands.StrPair("y", "ʎ"));
        //add(new CTCCommands.StrPair("z", "z"));
    }};

    public static final List<CTCCommands.StrPair> FULL_WIDTH = new ArrayList<CTCCommands.StrPair>() {{
        add(new CTCCommands.StrPair(" ", "　"));
        add(new CTCCommands.StrPair("!", "！"));
        add(new CTCCommands.StrPair("#", "＃"));
        add(new CTCCommands.StrPair("$", "＄"));
        add(new CTCCommands.StrPair("%", "％"));
        add(new CTCCommands.StrPair("&", "＆"));
        add(new CTCCommands.StrPair("'", "＇"));
        add(new CTCCommands.StrPair("(", "（"));
        add(new CTCCommands.StrPair(")", "）"));
        add(new CTCCommands.StrPair("*", "＊"));
        add(new CTCCommands.StrPair("+", "＋"));
        add(new CTCCommands.StrPair(",", "，"));
        add(new CTCCommands.StrPair("-", "－"));
        add(new CTCCommands.StrPair(".", "．"));
        add(new CTCCommands.StrPair("/", "／"));
        add(new CTCCommands.StrPair("0", "０"));
        add(new CTCCommands.StrPair("1", "１"));
        add(new CTCCommands.StrPair("2", "２"));
        add(new CTCCommands.StrPair("3", "３"));
        add(new CTCCommands.StrPair("4", "４"));
        add(new CTCCommands.StrPair("5", "５"));
        add(new CTCCommands.StrPair("6", "６"));
        add(new CTCCommands.StrPair("7", "７"));
        add(new CTCCommands.StrPair("8", "８"));
        add(new CTCCommands.StrPair("9", "９"));
        add(new CTCCommands.StrPair(":", "："));
        add(new CTCCommands.StrPair(";", "；"));
        add(new CTCCommands.StrPair("<", "＜"));
        add(new CTCCommands.StrPair("=", "＝"));
        add(new CTCCommands.StrPair(">", "＞"));
        add(new CTCCommands.StrPair("?", "？"));
        add(new CTCCommands.StrPair("@", "＠"));
        add(new CTCCommands.StrPair("A", "Ａ"));
        add(new CTCCommands.StrPair("B", "Ｂ"));
        add(new CTCCommands.StrPair("C", "Ｃ"));
        add(new CTCCommands.StrPair("D", "Ｄ"));
        add(new CTCCommands.StrPair("E", "Ｅ"));
        add(new CTCCommands.StrPair("F", "Ｆ"));
        add(new CTCCommands.StrPair("G", "Ｇ"));
        add(new CTCCommands.StrPair("H", "Ｈ"));
        add(new CTCCommands.StrPair("I", "Ｉ"));
        add(new CTCCommands.StrPair("J", "Ｊ"));
        add(new CTCCommands.StrPair("K", "Ｋ"));
        add(new CTCCommands.StrPair("L", "Ｌ"));
        add(new CTCCommands.StrPair("M", "Ｍ"));
        add(new CTCCommands.StrPair("N", "Ｎ"));
        add(new CTCCommands.StrPair("O", "Ｏ"));
        add(new CTCCommands.StrPair("P", "Ｐ"));
        add(new CTCCommands.StrPair("Q", "Ｑ"));
        add(new CTCCommands.StrPair("R", "Ｒ"));
        add(new CTCCommands.StrPair("S", "Ｓ"));
        add(new CTCCommands.StrPair("T", "Ｔ"));
        add(new CTCCommands.StrPair("U", "Ｕ"));
        add(new CTCCommands.StrPair("V", "Ｖ"));
        add(new CTCCommands.StrPair("W", "Ｗ"));
        add(new CTCCommands.StrPair("X", "Ｘ"));
        add(new CTCCommands.StrPair("Y", "Ｙ"));
        add(new CTCCommands.StrPair("Z", "Ｚ"));
        add(new CTCCommands.StrPair("[", "［"));
        add(new CTCCommands.StrPair("]", "］"));
        add(new CTCCommands.StrPair("^", "＾"));
        add(new CTCCommands.StrPair("_", "＿"));
        add(new CTCCommands.StrPair("`", "｀"));
        add(new CTCCommands.StrPair("a", "ａ"));
        add(new CTCCommands.StrPair("b", "ｂ"));
        add(new CTCCommands.StrPair("c", "ｃ"));
        add(new CTCCommands.StrPair("d", "ｄ"));
        add(new CTCCommands.StrPair("e", "ｅ"));
        add(new CTCCommands.StrPair("f", "ｆ"));
        add(new CTCCommands.StrPair("g", "ｇ"));
        add(new CTCCommands.StrPair("h", "ｈ"));
        add(new CTCCommands.StrPair("i", "ｉ"));
        add(new CTCCommands.StrPair("j", "ｊ"));
        add(new CTCCommands.StrPair("k", "ｋ"));
        add(new CTCCommands.StrPair("l", "ｌ"));
        add(new CTCCommands.StrPair("m", "ｍ"));
        add(new CTCCommands.StrPair("n", "ｎ"));
        add(new CTCCommands.StrPair("o", "ｏ"));
        add(new CTCCommands.StrPair("p", "ｐ"));
        add(new CTCCommands.StrPair("q", "ｑ"));
        add(new CTCCommands.StrPair("r", "ｒ"));
        add(new CTCCommands.StrPair("s", "ｓ"));
        add(new CTCCommands.StrPair("t", "ｔ"));
        add(new CTCCommands.StrPair("u", "ｕ"));
        add(new CTCCommands.StrPair("v", "ｖ"));
        add(new CTCCommands.StrPair("w", "ｗ"));
        add(new CTCCommands.StrPair("x", "ｘ"));
        add(new CTCCommands.StrPair("y", "ｙ"));
        add(new CTCCommands.StrPair("z", "ｚ"));
        add(new CTCCommands.StrPair("{", "｛"));
        add(new CTCCommands.StrPair("|", "｜"));
        add(new CTCCommands.StrPair("}", "｝"));
        add(new CTCCommands.StrPair("~", "～"));
    }};

    public static final List<CTCCommands.StrPair> MORSE = new ArrayList<CTCCommands.StrPair>() {{
        add(new CTCCommands.StrPair(" ", "/ "));
        add(new CTCCommands.StrPair(".", ".-.-.- "));
        add(new CTCCommands.StrPair(",", "--..-- "));
        add(new CTCCommands.StrPair(":", "---... "));
        add(new CTCCommands.StrPair("?", "..--.. "));
        add(new CTCCommands.StrPair("'", ".----. "));
        add(new CTCCommands.StrPair("-", "-....- "));
        add(new CTCCommands.StrPair("/", "-..-. "));
        add(new CTCCommands.StrPair("@", ".--.-. "));
        add(new CTCCommands.StrPair("=", "-...- "));
        add(new CTCCommands.StrPair("A", ".- "));
        add(new CTCCommands.StrPair("B", "-... "));
        add(new CTCCommands.StrPair("C", "-.-. "));
        add(new CTCCommands.StrPair("D", "-.. "));
        add(new CTCCommands.StrPair("E", ". "));
        add(new CTCCommands.StrPair("F", "..-. "));
        add(new CTCCommands.StrPair("G", "--. "));
        add(new CTCCommands.StrPair("H", ".... "));
        add(new CTCCommands.StrPair("I", ".. "));
        add(new CTCCommands.StrPair("J", ".--- "));
        add(new CTCCommands.StrPair("K", "-.- "));
        add(new CTCCommands.StrPair("L", ".-.. "));
        add(new CTCCommands.StrPair("M", "-- "));
        add(new CTCCommands.StrPair("N", "-. "));
        add(new CTCCommands.StrPair("O", "--- "));
        add(new CTCCommands.StrPair("P", ".--. "));
        add(new CTCCommands.StrPair("Q", "--.- "));
        add(new CTCCommands.StrPair("R", ".-. "));
        add(new CTCCommands.StrPair("S", "... "));
        add(new CTCCommands.StrPair("T", "- "));
        add(new CTCCommands.StrPair("U", "..- "));
        add(new CTCCommands.StrPair("V", "...- "));
        add(new CTCCommands.StrPair("W", ".-- "));
        add(new CTCCommands.StrPair("X", "-..- "));
        add(new CTCCommands.StrPair("Y", "-.-- "));
        add(new CTCCommands.StrPair("Z", "--.. "));
        add(new CTCCommands.StrPair("0", "----- "));
        add(new CTCCommands.StrPair("1", ".---- "));
        add(new CTCCommands.StrPair("2", "..--- "));
        add(new CTCCommands.StrPair("3", "...-- "));
        add(new CTCCommands.StrPair("4", "....- "));
        add(new CTCCommands.StrPair("5", "..... "));
        add(new CTCCommands.StrPair("6", "-.... "));
        add(new CTCCommands.StrPair("7", "--... "));
        add(new CTCCommands.StrPair("8", "---.. "));
        add(new CTCCommands.StrPair("9", "----. "));
    }};

    public static final List<CTCCommands.StrPair> GORDON = new ArrayList<CTCCommands.StrPair>() {{
        add(new CTCCommands.StrPair("a", "𝗮"));
        add(new CTCCommands.StrPair("b", "𝗯"));
        add(new CTCCommands.StrPair("c", "𝗰"));
        add(new CTCCommands.StrPair("d", "𝗱"));
        add(new CTCCommands.StrPair("e", "𝗲"));
        add(new CTCCommands.StrPair("f", "𝗳"));
        add(new CTCCommands.StrPair("g", "𝗴"));
        add(new CTCCommands.StrPair("h", "𝗵"));
        add(new CTCCommands.StrPair("i", "𝗶"));
        add(new CTCCommands.StrPair("j", "𝗷"));
        add(new CTCCommands.StrPair("k", "𝗸"));
        add(new CTCCommands.StrPair("l", "𝗹"));
        add(new CTCCommands.StrPair("m", "𝗺"));
        add(new CTCCommands.StrPair("n", "𝗻"));
        add(new CTCCommands.StrPair("o", "𝗼"));
        add(new CTCCommands.StrPair("p", "𝗽"));
        add(new CTCCommands.StrPair("q", "𝗾"));
        add(new CTCCommands.StrPair("r", "𝗿"));
        add(new CTCCommands.StrPair("s", "𝘀"));
        add(new CTCCommands.StrPair("t", "𝘁"));
        add(new CTCCommands.StrPair("u", "𝘂"));
        add(new CTCCommands.StrPair("v", "𝘃"));
        add(new CTCCommands.StrPair("w", "𝘄"));
        add(new CTCCommands.StrPair("x", "𝘅"));
        add(new CTCCommands.StrPair("y", "𝘆"));
        add(new CTCCommands.StrPair("z", "𝘇"));
        add(new CTCCommands.StrPair("A", "𝗔"));
        add(new CTCCommands.StrPair("B", "𝗕"));
        add(new CTCCommands.StrPair("C", "𝗖"));
        add(new CTCCommands.StrPair("D", "𝗗"));
        add(new CTCCommands.StrPair("E", "𝗘"));
        add(new CTCCommands.StrPair("F", "𝗙"));
        add(new CTCCommands.StrPair("G", "𝗚"));
        add(new CTCCommands.StrPair("H", "𝗛"));
        add(new CTCCommands.StrPair("I", "𝗜"));
        add(new CTCCommands.StrPair("J", "𝗝"));
        add(new CTCCommands.StrPair("K", "𝗞"));
        add(new CTCCommands.StrPair("L", "𝗟"));
        add(new CTCCommands.StrPair("M", "𝗠"));
        add(new CTCCommands.StrPair("N", "𝗡"));
        add(new CTCCommands.StrPair("O", "𝗢"));
        add(new CTCCommands.StrPair("P", "𝗣"));
        add(new CTCCommands.StrPair("Q", "𝗤"));
        add(new CTCCommands.StrPair("R", "𝗥"));
        add(new CTCCommands.StrPair("S", "𝗦"));
        add(new CTCCommands.StrPair("T", "𝗧"));
        add(new CTCCommands.StrPair("U", "𝗨"));
        add(new CTCCommands.StrPair("V", "𝗩"));
        add(new CTCCommands.StrPair("W", "𝗪"));
        add(new CTCCommands.StrPair("X", "𝗫"));
        add(new CTCCommands.StrPair("Y", "𝗬"));
        add(new CTCCommands.StrPair("Z", "𝗭"));
        add(new CTCCommands.StrPair("0", "𝟬"));
        add(new CTCCommands.StrPair("1", "𝟭"));
        add(new CTCCommands.StrPair("2", "𝟮"));
        add(new CTCCommands.StrPair("3", "𝟯"));
        add(new CTCCommands.StrPair("4", "𝟰"));
        add(new CTCCommands.StrPair("5", "𝟱"));
        add(new CTCCommands.StrPair("6", "𝟲"));
        add(new CTCCommands.StrPair("7", "𝟳"));
        add(new CTCCommands.StrPair("8", "𝟴"));
        add(new CTCCommands.StrPair("9", "𝟵"));
    }};

    public static final List<CTCCommands.StrPair> SMALL = new ArrayList<CTCCommands.StrPair>() {{
        add(new CTCCommands.StrPair("a", "ᴀ"));
        add(new CTCCommands.StrPair("b", "ʙ"));
        add(new CTCCommands.StrPair("c", "ᴄ"));
        add(new CTCCommands.StrPair("d", "ᴅ"));
        add(new CTCCommands.StrPair("e", "ᴇ"));
        add(new CTCCommands.StrPair("f", "ꜰ"));
        add(new CTCCommands.StrPair("g", "ɢ"));
        add(new CTCCommands.StrPair("h", "ʜ"));
        add(new CTCCommands.StrPair("i", "ɪ"));
        add(new CTCCommands.StrPair("j", "ᴊ"));
        add(new CTCCommands.StrPair("k", "ᴋ"));
        add(new CTCCommands.StrPair("l", "ʟ"));
        add(new CTCCommands.StrPair("m", "ᴍ"));
        add(new CTCCommands.StrPair("n", "ɴ"));
        add(new CTCCommands.StrPair("o", "ᴏ"));
        add(new CTCCommands.StrPair("p", "ᴘ"));
        add(new CTCCommands.StrPair("q", "ǫ"));
        add(new CTCCommands.StrPair("r", "ʀ"));
        //add(new CTCCommands.StrPair("s", "s"));
        add(new CTCCommands.StrPair("t", "ᴛ"));
        add(new CTCCommands.StrPair("u", "ᴜ"));
        add(new CTCCommands.StrPair("v", "ᴠ"));
        add(new CTCCommands.StrPair("w", "ᴡ"));
        add(new CTCCommands.StrPair("y", "ʏ"));
        add(new CTCCommands.StrPair("z", "ᴢ"));
    }};

    public static final List<CTCCommands.StrPair> SMALLER = new ArrayList<CTCCommands.StrPair>() {{
        add(new CTCCommands.StrPair("a", "ᵃ"));
        add(new CTCCommands.StrPair("b", "ᵇ"));
        add(new CTCCommands.StrPair("c", "ᶜ"));
        add(new CTCCommands.StrPair("d", "ᵈ"));
        add(new CTCCommands.StrPair("e", "ᵉ"));
        add(new CTCCommands.StrPair("f", "ᶠ"));
        add(new CTCCommands.StrPair("g", "ᵍ"));
        add(new CTCCommands.StrPair("h", "ʰ"));
        add(new CTCCommands.StrPair("i", "ᶦ"));
        add(new CTCCommands.StrPair("j", "ʲ"));
        add(new CTCCommands.StrPair("k", "ᵏ"));
        add(new CTCCommands.StrPair("l", "ˡ"));
        add(new CTCCommands.StrPair("m", "ᵐ"));
        add(new CTCCommands.StrPair("n", "ⁿ"));
        add(new CTCCommands.StrPair("o", "ᵒ"));
        add(new CTCCommands.StrPair("p", "ᵖ"));
        add(new CTCCommands.StrPair("q", "ᑫ"));
        add(new CTCCommands.StrPair("r", "ʳ"));
        add(new CTCCommands.StrPair("s", "ˢ"));
        add(new CTCCommands.StrPair("t", "ᵗ"));
        add(new CTCCommands.StrPair("u", "ᵘ"));
        add(new CTCCommands.StrPair("v", "ᵛ"));
        add(new CTCCommands.StrPair("w", "ʷ"));
        add(new CTCCommands.StrPair("x", "ˣ"));
        add(new CTCCommands.StrPair("y", "ʸ"));
        add(new CTCCommands.StrPair("z", "ᶻ"));
    }};

}
